# Generated by Django 4.2.6 on 2025-08-08 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0019_alter_patientdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name_plural': 'Gambar Radiologi Paru Paru'},
        ),
        migrations.CreateModel(
            name='GambarMikroskopikSputum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('diagnosisResult', models.TextField(blank=True, null=True)),
                ('limeImageResult', models.FileField(default=None, upload_to='')),
                ('imageDate', models.DateField(verbose_name='Tanggal Image diambil (mm/dd/yyyy)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hibahs.patientdata')),
            ],
            options={
                'verbose_name_plural': 'Gambar Mikroskopik Sputum',
            },
        ),
    ]
