# Generated by Django 4.2.6 on 2025-08-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibahs', '0020_alter_uploadedfile_options_gambarmikroskopiksputum'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedGambarMikroskopikSputum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/mikroskopik-image/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gambarmikroskopiksputum',
            name='file',
            field=models.FileField(upload_to='uploads/mikroskopik-image/'),
        ),
    ]
